### ISSUE TITLE
S3BucketConfigurationLambdaExecutionRole CloudFormation Resource missing log write perms

### ISSUE THREAD

**Issue by ChristianHart** [amazon-connect/amazon-connect-chat-ui-examples#27]
In the CloudFormation template for asyncCustomerChatUX the resource S3BucketConfigurationLambdaExecutionRole doesn't have permissions to write logs to CloudWatch. I ran into this issue when I ran into an error with the S3BucketConfigurationLambda function which I am currently troubleshooting. 

Please add the following lines to that lambda execution role so that it can write logs.
```
- Effect: "Allow"
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
```
